# Request

# What to do with the frame [add, move, clone, reparent, remove, rename, teach]
string command

# Name of the frame that is to be manipulated
string child_frame_id

# Desired frame to put the child frame in
string parent_frame_id

# New name, or the new name of the cloned child frame
string new_frame_id

# child_frame_id expressed in parent_frame_id
geometry_msgs/Transform transform

# Whether to manipulate the json file
# No persist for now, if you want to persist the change, edit the json file manually
# bool persist

# This map can contain additional data like mesh location, zone, etc.
string extra

---

# Reply
bool success
string info