# Request

# What to do with the frame [add, move, clone, reparent, remove, rename]
string command

# Name of the frame that is to be manipulated
string child_frame_id

# Desired frame to put the child frame in
string parent_frame_id

# New name, or the new name of the cloned child frame
string new_frame_id

# child_frame_id expressed in parent_frame_id
geometry_msgs/Transform transform

# Whether to manipulate the json file
# No persist for now, if you want to persist the change, edit the json file manually
# bool persist

# Threshold zone around the frame
# Could be used for example to indicate that the robot is at (near) the frame
float64 zone
---

# Reply
bool success
string info